### ISSUE TITLE
Hanging indefinitely with the default reload time set to 60 seconds 

### ISSUE THREAD

**Issue by MitchellMalleo** [llamasoft/Puca-Power#25]
Hey llamasoft,

Firstly, awesome job on this .js plugin. It makes trading on pucatrade just so much easier. :)

This is something I've noticed on my machine occasionally, especially on accounts with large collections. Sometimes I don't have the CPU power to aggregate all of the pages in the default 60 second time span, even on my more powerful machines. Would you consider changing the default time to possibly 120 or 180 seconds to alleviate this issue?

**Comment by llamasoft** [comment]
Hopefully the hang has been fixed with the latest release (v1.4.4).
As for refresh time, you can change that from the main option controls.  If you save your settings, it should persist between sessions.

That being said, the 60 seconds refresh timer is between when one refresh completes and the next one begins (see the `reloadComplete` function).  This ensures that a new refresh will never start until a previous one has been completed for the appropriate amount of time.

If you're still having issues with processing 10 pages of trades for alerts, you can modify the `pucaPower.maxPages` value to something lower than the default 10.

**Comment by MitchellMalleo** [comment]
Ahh okay great that makes sense, I'll go ahead and make the changes in my local fork. :+1:
