### ISSUE TITLE
Replace default alert MP3 with Ogg Vorbis

### ISSUE THREAD

**Issue by ghost** [llamasoft/Puca-Power#4]
Firefox and Chromium on Ubuntu (and probably other Linux distributions) are unable to play MP3 files by default. Since Puca Power's default alert sound is an MP3 file, audio alerts won't work. Ogg Vorbis files have better cross-platform support, so the default alert sound file should be an Ogg.

**Comment by llamasoft** [comment]
Turns out lack of MP3 support isn't a browser issue, it's an operating system issue (lack of MP3 decoder):
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP3
https://help.ubuntu.com/community/RestrictedFormats  

That being said, MP3 will be kept as the example alert sound because it has one of the [widest browser supports](http://www.w3schools.com/htmL/html5_audio.asp).

However, _that_ being said, feel free to use this: https://llamasoft.github.io/Puca-Power/alert.ogg  
In case you don't want to remember that, take the default alert sound URL and change the "mp3" extension to "ogg".
